"""esquema inicial

Revision ID: 5b9712e77e0c
Revises: 
Create Date: 2026-08-11 18:14:36.752624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9712e77e0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('unit_number', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('Casa', 'Departamento', name='unit_type', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('status', sa.Enum('Ocupada', 'Disponible', 'Mantenimiento', name='unit_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units'))
    )
    op.create_index(op.f('ix_units_status'), 'units', ['status'], unique=False)
    op.create_index(op.f('ix_units_unit_number'), 'units', ['unit_number'], unique=True)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Administrador', 'Operador', name='user_role', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('announcements',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Borrador', 'Publicado', name='announcement_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_announcements_author_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_index(op.f('ix_announcements_author_id'), 'announcements', ['author_id'], unique=False)
    op.create_index(op.f('ix_announcements_status'), 'announcements', ['status'], unique=False)
    op.create_table('incidents',
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('Baja', 'Media', 'Alta', name='incident_priority', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('status', sa.Enum('Pendiente', 'En proceso', 'Resuelta', name='incident_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_incidents_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_unit_id'), 'incidents', ['unit_id'], unique=False)
    op.create_table('residents',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('Activo', 'Inactivo', name='resident_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_residents_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_residents'))
    )
    op.create_index(op.f('ix_residents_full_name'), 'residents', ['full_name'], unique=False)
    op.create_index(op.f('ix_residents_status'), 'residents', ['status'], unique=False)
    op.create_index(op.f('ix_residents_unit_id'), 'residents', ['unit_id'], unique=False)
    op.create_table('payments',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('resident_id', sa.Uuid(), nullable=True),
    sa.Column('concept', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Pendiente', 'Pagado', 'Vencido', name='payment_status', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_amount_non_negative')),
    sa.CheckConstraint('period_month BETWEEN 1 AND 12', name=op.f('ck_payments_period_month_range')),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], name=op.f('fk_payments_resident_id_residents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_payments_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_period_year'), 'payments', ['period_year'], unique=False)
    op.create_index(op.f('ix_payments_resident_id'), 'payments', ['resident_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_unit_id'), 'payments', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_unit_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_resident_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_period_year'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_residents_unit_id'), table_name='residents')
    op.drop_index(op.f('ix_residents_status'), table_name='residents')
    op.drop_index(op.f('ix_residents_full_name'), table_name='residents')
    op.drop_table('residents')
    op.drop_index(op.f('ix_incidents_unit_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_announcements_status'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_author_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_unit_number'), table_name='units')
    op.drop_index(op.f('ix_units_status'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
